#lang racket

(require racket/trace)

;Exercise 1.9
;Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.

(define (inc a) (+ a 1))
(define (dec a) (- a 1))

(define (add1 a b)
  (if (= a 0)
      b
      (inc (add1 (dec a) b))))

(define (add2 a b)
  (if (= a 0)
      b
      (add2 (dec a) (inc b))))

(trace add1)
(add1 4 5)

(trace add2)
(add2 4 5)

;Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

; 第一种是 recursive，在当前层存在未计算完成的表达式 inc xxx
; 第二种是 iterative